---
functional:
  - Пользователь может создать игру, выбрав соперника из списка доступных пользователей
  - Пользователь может решить задачу на выбранном языке программирования
  - Система отображает код соперника в реальном времени
  - Пользователь получает уведомление о результатах выполнения тестов
  - Пользователь может общаться с соперником и зрителями через чат
  - Система фиксирует время, за которое каждый пользователь решает задачу
  - Пользователь может просматривать историю своих игр и результаты

non-functional:
  - Система должна поддерживать нагрузку до 1000 одновременных пользователей
  - Интерфейс пользователя должен быть доступен на мобильных и стационарных устройствах
  - Пользовательские данные должны храниться в безопасном и защищенном виде (шифрование, защита от SQL-инъекций)

implicit:
  - Интерфейс должен быть интуитивно понятным и легким в использовании
  - Система должна предоставлять возможность пользователям вносить свои предложения по улучшению игры

